import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Nav from '@/components/navigation/nav';
import './globals.css';
import { ProgressBar } from '@/components/progress/progress-bar';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('px-6 md:px-12 max-w-7xl mx-auto', `${inter.className}`)}
      >
        <ProgressBar className="fixed top-0 h-1 bg-sky-500">
          <Nav />
          {children}
        </ProgressBar>
      </body>
    </html>
  );
}
